.\" Macros
.ds PX \s-1LULU\s+1
.de EXAMPLE .\" Format de los ejemplos
.RS 10
.BR "\\$1"
.RE
..

.TH client 0.0.0 "21 de junio 2022"
.LO 8
.SH NAME
client \- monitorear y configurar SOCKSv5 server

.SH SYNOPSIS
.HP 10
.B client -u usuario:contraseña [-h] [-L dirección-de-management]
                [-P puerto-conf] [-v]
.SH DESCRIPTION
client es un cliente de LULU que es utilizado para monitorear y
configurar el server de SOCKSv5.

.SH OPTIONS


.\".IP "\fB\-d\fB"

        \-u usuario:contraseña
                Declara un usuario del server LULU con su contraseña.

        \-h
                Imprime la ayuda y termina.

        \-L dirección-de-management
                Establece la dirección donde servirá el servicio de management.                    
		Por defecto escucha únicamente en loopback.

        \-P puerto-conf
                Puerto TCP donde escuchará por conexiones entrante de protocolo.                   
		de configuración. Por defecto el valor es 8080.

        \-v
                Imprime información sobre la versión y termina.



.SH SEE ALSO
socks5d(8)

.SH AUTHOR
Lucas Dell'Isolla (ldellisola@itba.edu.ar)
Lucía Torrusio (ltorrusio@itba.edu.ar)
